
use MSHA;
IF OBJECT_ID (N'dbo.[mhsa_inspection]', N'U') IS NOT NULL
DROP TABLE dbo.[mhsa_inspection];
GO
CREATE TABLE [dbo].[mhsa_inspection](
	[active_sections] [varchar](500)  NULL,
	[acty_cd] [varchar](500)  NULL,
	[acty_desc] [varchar](500)  NULL,
	[beg_dt] [varchar](500) NULL,
	[bldg_constr_sites][varchar](500) NULL,
	[cal_qtr] [varchar](500)  NULL,
	[cal_yr] [varchar](500) NULL,
	[co_records] [varchar](500) NULL,
	[coal_metal_ind] [varchar](500) NULL,
	[controller_id][varchar](500)  NULL,
	[controller_name] [varchar](500)  NULL,
	[draglines] [varchar](500) NULL,
	[end_dt] [varchar](500) NULL,
	[event_no] [varchar](500) NULL , --Primary Key
	[explosive_storage] [varchar](500) NULL,
	[fiscal_qtr] [varchar](500)  NULL,
	[fiscal_yr] [varchar](500)  NULL,
	[idle_sections] [varchar](500) NULL,
	[impound_constr] [varchar](500) NULL,
	[impoundments] [varchar](500) NULL,
	[inspect_office_cd] [varchar](500) NULL,
	[major_constr] [varchar](500) NULL,
	[mine_id] [varchar](500) NULL,
	[misc_area] [varchar](500) NULL,
	[nbr_inspectors] [varchar](500) NULL,
	[operator_id] [varchar](500)  NULL,
	[operator_name] [varchar](500)  NULL,
	[outby_areas] [varchar](500) NULL,
	[program_area] [varchar](500) NULL,
	[refuse_piles] [varchar](500) NULL,
	[sample_cnt_air] [varchar](500) NULL,
	[sample_cnt_dustspot] [varchar](500) NULL,
	[sample_cnt_dustsurvey] [varchar](500) NULL,
	[sample_cnt_noise] [varchar](500) NULL,
	[sample_cnt_respdust] [varchar](500) NULL,
	[shaft_slope_sink] [varchar](500) NULL,
	[shafts_slopes] [varchar](500) NULL,
	[facility_mine] [varchar](500) NULL,
	[surf_ug_mine] [varchar](500) NULL,
	[total_insp_hours] [varchar](500) NULL,
	[total_on_site_hours] [varchar](500) NULL,
	[unclassified_constr] [varchar](500) NULL,
	[inspection_begin_year] [varchar](500) NULL,
	[inspection_end_year] [varchar](500) NULL,
	[state_abbr] [varchar](500) NULL,
	[sic_code_4_digit] [varchar](500) NULL,
	[mine_type_cd] [varchar](500) NULL,
	[curr_mine_nm] [varchar](500) NULL,
	[curr_stat_cd] [varchar](500) NULL,
	[curr_stat_dt] [varchar](500) NULL,
	[sig_sub_y] [varchar](500) NULL,
	[sig_sub_n] [varchar](500) NULL,
    /*FOREIGN KEY (violator_id) REFERENCES dbo.contractor(cntctr_id)*/
) --  ON [PRIMARY]
